import default_image from './assets/default_image.jpg'

export const data_list = [
    {

        name: 'rabee dad',
        role_type: 'leadership',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2023,
        month: 'april',
        country: 'UAE',
    },
    {
        name: 'Rabee waqd',
        role_type: 'sales front office',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2023,
        month: 'april',
        country: 'UAE',
    },
    {
        name: 'rabee cds',
        role_type: 'Sales Front Office',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2023,
        month: 'april',
        country: 'UAE',
    },
    {
        name: 'rabee 32ef',
        role_type: 'sales back office',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2022,
        month: 'march',
        country: 'KSA',
    },
    {
        name: 'rabee gk58',
        role_type: 'Sales Front Office',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2022,
        month: 'october',
        country: 'KSA',
    },
    {
        name: 'rabee klnker',
        role_type: 'support function',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2022,
        month: 'november',
        country: 'BAHRAIN',
    },
    {
        name: 'rabee nkerk',
        role_type: 'distribution centre',
        image: default_image,
        old_designation: 'assetance',
        new_designation: 'manager',
        year: 2022,
        month: 'december',
        country: 'KUWAIT',
    },
]