
import a139410 from '../assets/employee_images/139410.webp';
import a150614 from '../assets/employee_images/150614.webp';
import a150704 from '../assets/employee_images/150704.webp';
import a116370 from '../assets/employee_images/116370.webp';
import a127349 from '../assets/employee_images/127349.webp';
import a128173 from '../assets/employee_images/128173.webp';

export const bahrain_list = [

    {
        id: '139410',
        name: 'Jay Mallo',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'BAHRAIN',
        image: a139410,
      },
      {
        id: '150614',
        name: 'Katherine Tambanillo',
        role_type: 'Sales Front Office',
        new_role: 'In-store Trainer',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'BAHRAIN',
        image: a150614,
      },
      {
        id: '150704',
        name: 'Mylene Mae Mausisa',
        role_type: 'Sales Front Office',
        new_role: 'In-store Trainer',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'BAHRAIN',
        image: a150704,
      },
      {
        id: '101617',
        name: 'Shankar Bhoominathan',
        role_type: 'Support Function',
        new_role: 'Executive - Loss Prevention',
        year: '2023',
        month: 'April',
        brand: 'Loss Prevention',
        country: 'Bahrain',
        // image: a101617,
      },
      {
        id: '107874',
        name: 'Alma Domer',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'Tommy Hilfiger',
        country: 'Bahrain',
        // image: a107874,
      },
      {
        id: '107889',
        name: 'Hawa Akuha',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'Call It Spring',
        country: 'Bahrain',
        // image: a107889,
      },
      {
        id: '107918',
        name: 'Maryam Sharif',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'May',
        brand: 'Beverly Hills Polo Club',
        country: 'Bahrain',
        // image: a107918,
      },
      {
        id: '113973',
        name: 'Regine Potueco',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'ALDO',
        country: 'Bahrain',
        // image: a113973,
      },
      {
        id: '113975',
        name: 'Sameer Krishnapura',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2023',
        month: 'April',
        brand: 'Aeropostale',
        country: 'Bahrain',
        // image: a113975,
      },
      {
        id: '116370',
        name: 'Sherif Abdallah Ramadan Elsayed Moustafa',
        role_type: 'Sales Front Office',
        new_role: 'Cluster Manager',
        year: '2023',
        month: 'March',
        brand: 'Beverly Hills Polo Club',
        country: 'Bahrain',
        image: a116370,
      },
      {
        id: '117211',
        name: 'Sashika Wettappulige',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'Crocs',
        country: 'Bahrain',
        // image: a117211,
      },
      {
        id: '122999',
        name: 'lrene Jumbo',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Visual Merchandiser',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Bahrain',
        // image: a122999,
      },
      {
        id: '124003',
        name: 'Haya Ali',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'Beverly Hills Polo Club',
        country: 'Bahrain',
        // image: a124003,
      },
      {
        id: '125175',
        name: 'Mohamed Rinosh',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'Aeropostale',
        country: 'Bahrain',
        // image: a125175,
      },
      {
        id: '125594',
        name: 'Amit Katal',
        role_type: 'Sales Front Office',
        new_role: 'Store Supervisor',
        year: '2023',
        month: 'April',
        brand: 'R&B',
        country: 'Bahrain',
        // image: a125594,
      },
      {
        id: '125659',
        name: 'Shella Vicente',
        role_type: 'Sales Front Office',
        new_role: 'Store Supervisor',
        year: '2023',
        month: 'April',
        brand: 'R&B',
        country: 'Bahrain',
        // image: a125659,
      },
      {
        id: '126135',
        name: 'Prakash Sharma',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'April',
        brand: 'CCC',
        country: 'Bahrain',
        // image: a126135,
      },
      {
        id: '144593',
        name: 'Suraj Thakur',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2023',
        month: 'April',
        brand: 'R&B',
        country: 'Bahrain',
        // image: a144593,
      },
      {
        id: '127349',
        name: 'Roderick Opena',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'January',
        brand: 'LC Waikiki',
        country: 'BAHRAIN',
        image: a127349,
      },
      {
        id: '128173',
        name: 'Kaysian Lyn Pino',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'January',
        brand: 'Skechers',
        country: 'BAHRAIN',
        image: a128173,
      },
      {
        id: '100216',
        name: 'Dheeraj  Ratnani',
        role_type: 'Leadership',
        new_role: 'Country Manager',
        year: '2022',
        brand: 'Regional Office',
        country: 'BAHRAIN',
      },
      {
        id: '107655',
        name: 'Selvendran Subramanian',
        role_type: 'Support Function',
        new_role: 'Manager - ICT',
        year: '2022',
        brand: 'Information and Communication Technology',
        country: 'BAHRAIN',
      },
      {
        id: '107632',
        name: 'Naveen Rai Kulshekar',
        role_type: 'Support Function',
        new_role: 'Assistant Manager - Brand & Operations',
        year: '2022',
        brand: 'Regional Office',
        country: 'BAHRAIN',
      },
      {
        id: '107635',
        name: 'Steffi D Cruz',
        role_type: 'Support Function',
        new_role: 'Senior Executive - Human Capital',
        year: '2022',
        brand: 'Human Capital',
        country: 'BAHRAIN',
      },
      {
        id: '107646',
        name: 'Abdul Mansoor',
        role_type: 'Distribution Centre',
        new_role: 'Warehouse Supervisor',
        year: '2022',
        brand: 'Distribution Centre',
        country: 'BAHRAIN',
      },
      {
        id: '107649',
        name: 'Sreejith Kavullapurayil',
        role_type: 'Support Function',
        new_role: 'Manager - Inventory & Logistics',
        year: '2022',
        brand: 'Distribution Centre',
        country: 'BAHRAIN',
      },
      {
        id: '107653',
        name: 'Sandeep Kumar',
        role_type: 'Support Function',
        new_role: 'Project Assistant',
        year: '2022',
        brand: 'Projects',
        country: 'BAHRAIN',
      },
      {
        id: '107675',
        name: 'Prajwol Giri',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Beverly Hills Polo Club',
        country: 'BAHRAIN',
      },
      {
        id: '107713',
        name: 'Christopher Samaniego Santos',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Charles & Keith',
        country: 'BAHRAIN',
      },
      {
        id: '107721',
        name: 'Hassan Ahmed Ebrahim',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Visual Merchandising',
        year: '2022',
        brand: 'Tommy Hilfiger',
        country: 'BAHRAIN',
      },
      {
        id: '107816',
        name: 'Pawan Tamang',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Beverly Hills Polo Club',
        country: 'BAHRAIN',
      },
      {
        id: '107835',
        name: 'Abu Ansari',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Skechers',
        country: 'BAHRAIN',
      },
      {
        id: '107898',
        name: 'Ismayeel Kandy',
        role_type: 'Support Function',
        new_role: 'Merchandiser',
        year: '2022',
        brand: 'Regional Office',
        country: 'BAHRAIN',
      },
      {
        id: '107931',
        name: 'Docus Namatovu',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Skechers',
        country: 'BAHRAIN',
      },
      {
        id: '111988',
        name: 'Justin Singh',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'BAHRAIN',
      },
      
      {
        id: '114543',
        name: 'Muhammad Ahmad',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Dollar Plus',
        country: 'BAHRAIN',
      },
      {
        id: '119702',
        name: 'Amal  Pambingal',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Birkenstock',
        country: 'BAHRAIN',
      },
      {
        id: '119959',
        name: 'Ahmed Fazeel',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Skechers',
        country: 'BAHRAIN',
      },
      {
        id: '127680',
        name: 'Ismail Nazeer',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'BAHRAIN',
      },
      



]