import a130831 from '../assets/employee_images/130831.webp';
import a134581 from '../assets/employee_images/134581.webp';
import a145607 from '../assets/employee_images/145607.webp';
import a150932 from '../assets/employee_images/150932.webp';

export const ksa_list = [
  {
    id: '110148',
    name: 'Mohamed Salam',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'August',
    brand: 'Naturalizer',
    country: 'KSA',
    // image: a110148,
  },
  {
    id: '114858',
    name: 'Mamdouh Khaled Al Enenzi',
    role_type: 'Support Function',
    new_role: 'Executive - Loss Prevention',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    IJP: true,
  },
  {
    id: '129033',
    name: 'Mohd Rizwan Abdul Jabbar',
    role_type: 'Sales Front Office',
    new_role: 'Mall Manager',
    year: '2023',
    month: 'August',
    brand: 'R&B',
    country: 'KSA',
    // image: a129033,
  },
  {
    id: '109777',
    name: 'Genecis Amata',
    role_type: 'Sales Front Office',
    new_role: 'Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a109777,
  },
  {
    id: '149797',
    name: 'Krish Shiv Rujan Kaur',
    role_type: 'Sales Front Office',
    new_role: 'Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a149797,
  },
  {
    id: '123051',
    name: 'Abdulrahman Aljahni',
    role_type: 'Sales Front Office',
    new_role: 'Multi Unit Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a123051,
  },
  {
    id: '109560',
    name: 'Adil Ahmed',
    role_type: 'Sales Back Office',
    new_role: 'Assistant Manager - Brand & Operations',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a109560,
  },
  {
    id: '109561',
    name: 'Joey Sta Maria',
    role_type: 'Sales Back Office',
    new_role: 'Senior Visual Merchandiser',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a109561,
  },
  {
    id: '109566',
    name: 'Nazr Fareed Javaid',
    role_type: 'Sales Back Office',
    new_role: 'Assistant Manager - Brand & Operations',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a109566,
  },
  {
    id: '110205',
    name: 'Mahmoud Muhammad',
    role_type: 'Sales Front Office',
    new_role: 'Visual Merchandiser',
    year: '2023',
    month: 'August',
    brand: 'Naturalizer',
    country: 'KSA',
    // image: a110205,
  },
  {
    id: '110438',
    name: 'Jabran Dar',
    role_type: 'Sales Front Office',
    new_role: 'Area Sales Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a110438,
  },
  {
    id: '110464',
    name: 'Abdullah Jamali',
    role_type: 'Sales Front Office',
    new_role: 'Area Sales Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a110464,
  },
  {
    id: '110995',
    name: 'Pralay Gorai',
    role_type: 'Sales Front Office',
    new_role: 'Area Sales Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a110995,
  },
  {
    id: '116895',
    name: 'Safwan Alrefaie',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a116895,
  },
  {
    id: '111723',
    name: 'Adel Alanazi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a111723,
  },
  {
    id: '113625',
    name: 'Eissa Ali Geesa',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a113625,
  },
  {
    id: '116639',
    name: 'Fatimah Alyami',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a116639,
  },
  {
    id: '127789',
    name: 'Osama Alsuhaymi',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a127789,
  },
  {
    id: '122870',
    name: 'Hamood Jaradah',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a122870,
  },
  {
    id: '123730',
    name: 'Mohannad Alshahrani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Adidas',
    country: 'KSA',
    // image: a123730,
  },
  {
    id: '130641',
    name: 'Rana Singh Magar',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a130641,
  },
  {
    id: '130947',
    name: 'Dexter Jacob Viernes',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a130947,
  },
  {
    id: '130952',
    name: 'Dennis Monte Abarratigue',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a130952,
  },
  {
    id: '131304',
    name: 'Ricky Certeza Atienza',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a131304,
  },
  {
    id: '128714',
    name: 'Khaled Mohammed Abdulrahman Alrezan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a128714,
  },
  {
    id: '133642',
    name: 'Mohamed Harbi Younis Abduhalim',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a133642,
  },
  {
    id: '133644',
    name: 'Mohamed Abdelwahab Ismail Ahmed',
    role_type: 'Sales Front Office',
    new_role: 'Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a133644,
  },
  {
    id: '132769',
    name: 'Atyaf Mansour Ibrahim Alshaikh',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Adidas',
    country: 'KSA',
    // image: a132769,
  },
  {
    id: '133847',
    name: 'Hameed Ibrahim Almuhsen',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Adidas',
    country: 'KSA',
    // image: a133847,
  },
  {
    id: '133975',
    name: 'Ibrahim Mohammed Saad Alhazzani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a133975,
  },
  {
    id: '133977',
    name: 'Hail Saed Saeed Alharthi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'The Athletes Co',
    country: 'KSA',
    // image: a133977,
  },
  {
    id: '135258',
    name: 'Hanan Aljezani',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135258,
  },
  {
    id: '135286',
    name: 'Abdullah Ghazali',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135286,
  },
  {
    id: '135320',
    name: 'Mohammed Saleh',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135320,
  },
  {
    id: '135342',
    name: 'Mohammed Anver',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135342,
  },
  {
    id: '135349',
    name: 'Mohammed Marikkar',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135349,
  },
  {
    id: '134399',
    name: 'Man Sami Mohammed Jokab',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a134399,
  },
  {
    id: '135442',
    name: 'Osamah Matar Alshahrani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'August',
    brand: 'Skechers',
    country: 'KSA',
    // image: a135442,
  },
  {
    id: '135745',
    name: 'Youssef Abouelela',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135745,
  },
  {
    id: '135819',
    name: 'Shah Jalal',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a135819,
  },
  {
    id: '135459',
    name: 'Omar Maatouq Omar Bahumaish',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a135459,
  },
  {
    id: '136669',
    name: 'Khloud Alqahtani',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a136669,
  },
  {
    id: '136625',
    name: 'Jawaied Hussain Alshwaker',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Adidas',
    country: 'KSA',
    // image: a136625,
  },
  {
    id: '136780',
    name: 'Mohammed Sohail',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a136780,
  },
  {
    id: '137427',
    name: 'Abdullah Adeeb Alrashed',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a137427,
  },
  {
    id: '137711',
    name: 'Fatimah Mahdi Al Qowaisim',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a137711,
  },
  {
    id: '137755',
    name: 'Sanjeewa Samarasekara',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a137755,
  },
  {
    id: '137946',
    name: 'Juber Ahmed',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a137946,
  },
  {
    id: '137958',
    name: 'Tamer Abulhamid',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a137958,
  },
  {
    id: '138024',
    name: 'Gulam Mohammed',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a138024,
  },
  {
    id: '138353',
    name: 'Ruba Ahmad Abdullah',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'August',
    brand: 'Rituals',
    country: 'KSA',
    // image: a138353,
  },
  {
    id: '139123',
    name: 'Abdulhameed Nabeel Abdulhameed Banjer',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a139123,
  },
  {
    id: '139301',
    name: 'Earvin Novesteras',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a139301,
  },
  {
    id: '139726',
    name: 'Abdulaziz Ahmed Musa Asiri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a139726,
  },
  {
    id: '139988',
    name: 'Rahayf Hammad Hamedan Al Johani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a139988,
  },
  {
    id: '140318',
    name: 'Jumana Jamal Al Hilal',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Adidas',
    country: 'KSA',
    // image: a140318,
  },
  {
    id: '141506',
    name: 'Ahmed Omar',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a141506,
  },
  {
    id: '141611',
    name: 'Anis Lawati',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a141611,
  },
  {
    id: '141769',
    name: 'Anmol Shrestha',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a141769,
  },
  {
    id: '142711',
    name: 'Aziz Daghri',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a142711,
  },
  {
    id: '142816',
    name: 'Nedar Mohammed Ibrahim Khan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'August',
    brand: 'Rituals',
    country: 'KSA',
    // image: a142816,
  },
  {
    id: '142890',
    name: 'Abdulelah Zaid Abu Hubaysh',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a142890,
  },
  {
    id: '142903',
    name: 'Ziyad Alothayqi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a142903,
  },
  {
    id: '143259',
    name: 'Muhammadu Nahfees',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a143259,
  },
  {
    id: '143261',
    name: 'Shehan Madusanka',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a143261,
  },
  {
    id: '143502',
    name: 'Wajd Alzahrani',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a143502,
  },
  {
    id: '143667',
    name: 'Ayman Mahmoud',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a143667,
  },
  {
    id: '144020',
    name: 'Abdulrahman Alshahrani',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a144020,
  },
  {
    id: '144026',
    name: 'Muhannad Albeshi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a144026,
  },
  {
    id: '145457',
    name: 'Eyad Alshmeeri',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a145457,
  },
  {
    id: '145542',
    name: 'Asad Abbas',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a145542,
  },
  {
    id: '145591',
    name: 'Adnan Abbasi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a145591,
  },
  {
    id: '145670',
    name: 'Zainab Hamad Alfadhel',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
    // image: a145670,
  },
  {
    id: '145714',
    name: 'Ahmed Abdulsalam',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a145714,
  },
  {
    id: '146128',
    name: 'Mohammed Naji Albashah',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Adidas',
    country: 'KSA',
    // image: a146128,
  },
  {
    id: '146792',
    name: 'Awais Abbasi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a146792,
  },
  {
    id: '146814',
    name: 'Adham Abdelmaksoud',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a146814,
  },
  {
    id: '146816',
    name: 'Mohamed Bayomi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a146816,
  },
  {
    id: '146920',
    name: 'Ahmed Azab',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a146920,
  },
  {
    id: '147169',
    name: 'Kiran Shakariya',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a147169,
  },
  {
    id: '147845',
    name: 'Nouf Al Ruwaithi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a147845,
  },
  {
    id: '149584',
    name: 'Elsayed Mohamed Mohamed Elrashidy',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a149584,
  },
  {
    id: '149788',
    name: 'Umar Imran Nachan',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a149788,
  },
  {
    id: '110682',
    name: 'Romer Liat',
    role_type: 'Sales Front Office',
    new_role: 'Visual Merchandiser',
    year: '2023',
    month: 'July ',
    brand: 'Skechers',
    country: 'KSA',
    // image: a110682,
  },
  {
    id: '151577',
    name: 'Saud Alzafaran  ',
    role_type: 'Sales Front Office',
    new_role: 'In-store Trainer',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a151577,
  },
  {
    id: '151898',
    name: 'Bader Mohammed B Barnawi',
    role_type: 'Sales Front Office',
    new_role: 'Sales Associate',
    year: '2023',
    month: 'July ',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
    // image: a151898,
  },
  {
    id: '108092',
    name: 'Amit Kumar',
    role_type: 'Support Function',
    new_role: 'Head of Projects',
    year: '2023',
    month: 'May',
    brand: 'Projects',
    country: 'KSA',
  },
  {
    id: '109618',
    name: 'Alex Bruto',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Manager - Restaurant',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '109825',
    name: 'Sameer Hassan Muhammed',
    role_type: 'Support Function',
    new_role: 'Assistant Manager - Business Development',
    year: '2023',
    month: 'June',
    brand: 'Regional Office',
    country: 'KSA',
  },
  {
    id: '109979',
    name: 'Ali Abdul Jawad',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '110115',
    name: 'Mostafa Mahmoued Ismail',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '110162',
    name: 'Amro Bukur',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'May',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
  },
  {
    id: '111162',
    name: 'Muaadh Jalil Saeed',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'March',
    brand: 'Tim Hortons',
    country: 'KSA',
  },
  {
    id: '111219',
    name: 'Mohamed Haleem',
    role_type: 'Support Function',
    new_role: 'Project Engineer',
    year: '2023',
    month: 'June',
    brand: 'Projects',
    country: 'KSA',
  },
  {
    id: '111436',
    name: 'Shanu Nadeem',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '113977',
    name: 'Raees Khan',
    role_type: 'Sales Front Office',
    new_role: 'Area Sales Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '115206',
    name: 'Jaber Hazazi',
    role_type: 'Support Function',
    new_role: 'Executive - Loss Prevention',
    year: '2023',
    month: 'March',
    brand: 'Tim Hortons',
    country: 'KSA',
  },
  {
    id: '123921',
    name: 'Muhsin Mishari',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '124490',
    name: 'Wafa Alharbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'TOMS',
    country: 'KSA',
  },
  {
    id: '124930',
    name: 'Ahmed Abdulaziz Aljuraid',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '125007',
    name: 'Basem Ali Khogeer',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '126242',
    name: 'Ghouthyah Begum Shareef',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Ardene',
    country: 'KSA',
  },
  {
    id: '127902',
    name: 'Nawaf Almuwallad',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '128132',
    name: 'Vinod Sreenivasa',
    role_type: 'Sales Back Office',
    new_role: 'Manager - Merchandising',
    year: '2023',
    month: 'May',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '128135',
    name: 'Joel Ducante',
    role_type: 'Sales Back Office',
    new_role: 'Manager - Visual Merchandising',
    year: '2023',
    month: 'May',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '128685',
    name: 'Jabrah Atiah Almarhabi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '128797',
    name: 'Abdullah Altaroti',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'May',
    brand: 'Calvin Klein',
    country: 'KSA',
  },
  {
    id: '129458',
    name: 'Abdulelah Hesham Abdulqader Farhat',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '129887',
    name: 'Najah Zaid Saed',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Naturalizer',
    country: 'KSA',
  },
  {
    id: '130658',
    name: 'Abdullah Makki Mohammed Albaloushi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '130801',
    name: 'Bikki Lama',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '133277',
    name: 'Narayan G.C',
    role_type: 'Sales Front Office',
    new_role: 'Senior waiter ',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '133376',
    name: 'Mohamed Lafir',
    role_type: 'Sales Front Office',
    new_role: 'Sous Chef',
    year: '2023',
    month: 'May',
    brand: 'Jamies Italian',
    country: 'KSA',
  },
  {
    id: '133770',
    name: 'Salin Manandhar',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Manager - Restaurant',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '133772',
    name: 'Deewar Thapa',
    role_type: 'Sales Front Office',
    new_role: 'Senior Line Cook',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '133776',
    name: 'Sajin Gurung',
    role_type: 'Sales Front Office',
    new_role: 'Senior Barista',
    year: '2023',
    month: 'May',
    brand: 'Jamies Italian',
    country: 'KSA',
  },
  {
    id: '133850',
    name: 'Mohammed Kadhem Alradi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '134027',
    name: 'Reem Abdullah Muhammad Almasawe',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '134236',
    name: 'Khaled Nasser Fahad Aluhaym',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '134683',
    name: 'Osama Mohammed Adam Alkenani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '134926',
    name: 'Wael Hakem',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'April',
    brand: 'Tim Hortons',
    country: 'KSA',
  },
  {
    id: '134940',
    name: 'Muhanned Mohammed Salem Alqarni',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '135007',
    name: 'Fares Abdulaziz Maqbool Aluamani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '135129',
    name: 'Ahmed Khaled Ramadan Alsualimi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '135135',
    name: 'Abud Abdullah Dhafer Alqahtani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '135849',
    name: 'Lameah Mohamued Alqahet',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '135862',
    name: 'Hussain Fuad Althawab',
    role_type: 'Support Function',
    new_role: 'Loss Prevention Associate',
    year: '2023',
    month: 'June',
    brand: 'Loss Prevention',
    country: 'KSA',
  },
  {
    id: '135888',
    name: 'Ehsanullah Ateequllah',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '136194',
    name: 'Hasan Sulaiman Ahmed Abdulhameed',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '136666',
    name: 'Abdullah Naif Alosaimi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '136936',
    name: 'Salman Aidarous Aidarous Alsanibi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '137076',
    name: 'Asmah Abdullah Albassy',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '137425',
    name: 'Salman Abdulaziz Altilasi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '137771',
    name: 'Bharat Sunar',
    role_type: 'Sales Front Office',
    new_role: 'Senior Line Cook',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '138246',
    name: 'Ashwaq Ibrahim Haddadi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '138538',
    name: 'Dexter Descallar',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '138540',
    name: 'Jannjo Catuira',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '138542',
    name: 'Ricardo Jr. Ortega',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'May',
    brand: 'Jamies Italian',
    country: 'KSA',
  },
  {
    id: '139135',
    name: 'Wejdan Helal Muawid Al Harbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '139190',
    name: 'Rabab Mohammed Yousef Barqawi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '139300',
    name: 'Tuflah Saad Ibrahim Al Shamri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '139327',
    name: 'Reem Abdullah Ali Al Dawsari',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '139804',
    name: 'Megh Singh',
    role_type: 'Support Function',
    new_role: 'Senior Manager - Accounts & Finance',
    year: '2023',
    month: 'May',
    brand: 'Country Manager Office',
    country: 'KSA',
  },
  {
    id: '140374',
    name: 'Fatima Mghawi Ali Al Asiri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '140635',
    name: 'Wala Mohammed Al Hafaf',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '140976',
    name: 'Lujin Braa Al Thabtah',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Naturalizer',
    country: 'KSA',
  },
  {
    id: '141976',
    name: 'Khalid Mohammed Aldossari',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '142756',
    name: 'Aaqib Farooq Dar',
    role_type: 'Sales Front Office',
    new_role: 'Senior Barista',
    year: '2023',
    month: 'May',
    brand: 'Jamies Italian',
    country: 'KSA',
  },
  {
    id: '142758',
    name: 'Raunak Panday',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '142764',
    name: 'Neville V Mascarenhas',
    role_type: 'Sales Front Office',
    new_role: 'Demi Chef De Partie',
    year: '2023',
    month: 'May',
    brand: 'Jamies Italian',
    country: 'KSA',
  },
  {
    id: '142937',
    name: 'Khalid Suliman Mutlq Alharbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '143777',
    name: 'John Mauro Nardo',
    role_type: 'Sales Front Office',
    new_role: 'Line Cook',
    year: '2023',
    month: 'May',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '143824',
    name: 'Tariq Ebraheem Hasan Haneen',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '144682',
    name: 'Nedaa Khalid Mohammed Althaqafi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Naturalizer',
    country: 'KSA',
  },
  {
    id: '144892',
    name: 'Khitam Salih Alharbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '144992',
    name: 'Hanan Abdullah Mohaimeed',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '147313',
    name: 'Fatimah bakheet Alzubaidi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '149831',
    name: 'Ahmed Rami Ali Omdah',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '150155',
    name: 'Sharawq Hadi Yahya Mubarak',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'TOMS',
    country: 'KSA',
  },
  {
    id: '150604',
    name: 'Bader Jaser Hmoud Al jaser',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '150680',
    name: 'Shahd Nowar S Alneqael',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '150938',
    name: 'Shuruq Sultan Mahmaas Almutairi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'April',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '150966',
    name: 'Mashael Saeed Alqhtani',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '151879',
    name: 'Malak Fahad K Aljoudi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Naturalizer',
    country: 'KSA',
  },
  {
    id: '154998',
    name: 'Ghaythah Abdullah Hasan Alshehri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Naturalizer',
    country: 'KSA',
  },
  {
    id: '157662',
    name: 'Abdulrahim Ali Ramadan Alzahrani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'May',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '130831',
    name: 'Ali Akbar Mansur',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'February',
    brand: 'Tim Hortons',
    country: 'KSA',
    image: a130831,
  },
  {
    id: '137220',
    name: 'Abdullah Alotabi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'February',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '109829',
    name: 'Abdul Poonthodi',
    role_type: 'Sales Back Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Naturalizer',
    country: 'KSA',
  },
  {
    id: '109853',
    name: 'Mohammed Museen',
    role_type: 'Sales Back Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '110130',
    name: 'Mohammad Mokhtar',
    role_type: 'Sales Back Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
    // image: a110130,
  },
  {
    id: '110470',
    name: 'Siddiq Ahmad',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '113157',
    name: 'Vikas Ganpat Kamble',
    role_type: 'Sales Back Office',
    new_role: 'Assistant Manager - Supply Chain',
    year: '2023',
    month: 'January',
    brand: 'Jamies Italian',
    country: 'KSA',
  },
  {
    id: '114671',
    name: 'Maha Nahi Al Otaibi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '119390',
    name: 'Abdulmajid Alotaibi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '128345',
    name: 'Khadijah Salem Omer Ba Medhen',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Ardene',
    country: 'KSA',
  },
  {
    id: '134581',
    name: 'Murtadha AlSkiri',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'January',
    brand: 'Tim Hortons',
    country: 'KSA',
    image: a134581,
  },
  {
    id: '134889',
    name: 'Amal Samir Jamaan Jamaan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '135517',
    name: 'Osamah Wadid Alanazi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '136644',
    name: 'Raneem Albogami',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '137116',
    name: 'ABDULLAH ADIL AHMED ALMUFTI',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '137509',
    name: 'Meshal Othman Mubarak Alharkan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '137777',
    name: 'Ali Mohammed Hassan Alqahtani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '137857',
    name: 'Moniah Albadah',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '138658',
    name: 'Mohammed Amin',
    role_type: 'Sales Front Office',
    new_role: 'Manager - Catering',
    year: '2023',
    month: 'January',
    brand: 'Tim Hortons',
    country: 'KSA',
    // image: a138658,
  },
  {
    id: '139122',
    name: 'Ragdan Hassan Saeed Ba Khashwin',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '139339',
    name: 'Abdulelah Mohammed Al Sharahili',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '139870',
    name: 'Muath Sulaiman Mutlaq Al Harbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '140492',
    name: 'Yousif Ahmed Hamid Al Harbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '140726',
    name: 'Qusai Mohammed Abdullah Mathkour',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '141831',
    name: 'Turki Sultan Aloshaywi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '141935',
    name: 'Falwah Hassan Bati Aldosari',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '141947',
    name: 'Hessah Fahad Jeri Alotabi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '142364',
    name: 'Hadeel Mohammed Alfaifi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '143534',
    name: 'Essa Ali Mohammed Kaabi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '143697',
    name: 'Abdullah Abed Abdullah Alghamdi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '144282',
    name: 'Bashayer Awad Dubian Alzarfani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KSA',
  },
  {
    id: '144450',
    name: 'Maha Husain Algahtani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '145607',
    name: 'Hamad Ahmed Altulyan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
    image: a145607,
  },
  {
    id: '145831',
    name: 'Shaden Ali Alsalman',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '146135',
    name: 'Badryah Muhammad Alotaibi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '146516',
    name: 'Amwal Azim Alruwaili',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '146678',
    name: 'Fatimah Ali Alasiri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '147955',
    name: 'Abdulaziz Ahmed Embarak Alzahrani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '150932',
    name: 'Faisal Parkar',
    role_type: 'Support Function',
    new_role: 'Head of IT - Tim Hortons',
    year: '2023',
    month: 'January',
    brand: 'Tim Hortons',
    country: 'KSA',
    image: a150932,
  },
  {
    id: '151150',
    name: 'Muteb Abdullah Al bobkir',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '151253',
    name: 'Saleh Ahmed Alsalem',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '154738',
    name: 'Mohammad Irfan Ansari',
    role_type: 'Ecommerce',
    new_role: 'Last Mile Supervisor',
    year: '2023',
    month: 'January',
    brand: '6th Street',
    country: 'KSA',
    // image: a154738,
  },
  {
    id: '156000',
    name: 'Md Abdul Kareem',
    role_type: 'Sales Back Office',
    new_role: 'Sales & Operations Manager',
    year: '2023',
    month: 'January',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '140511',
    name: 'Ahmad Abdulaziz Al Jarba',
    role_type: 'Support Function',
    new_role: 'Manager - Marketing',
    year: '2022',
    brand: 'Marketing',
    country: 'KSA',
  },
  {
    id: '107634',
    name: 'Shina Mammen',
    role_type: 'Support Function',
    new_role: 'Manager - Human Capital',
    year: '2022',
    brand: 'Human Capital',
    country: 'KSA',
  },
  {
    id: '109543',
    name: 'Fahad Chaudry',
    role_type: 'Support Function',
    new_role: 'Assistant Manager - MIS & Budgeting',
    year: '2022',
    brand: 'Accounts and Finance',
    country: 'KSA',
  },
  {
    id: '109549',
    name: 'Sachin Wagh',
    role_type: 'Sales Back Office',
    new_role: 'Assistant Manager - Brand & Operations',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '110036',
    name: 'Ali Abdul Aziz',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2022',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '110166',
    name: 'Abdurahman Mohammed',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '110312',
    name: 'Muzaffar Ahmed',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2022',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '110465',
    name: 'Hassan udyawar',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2022',
    brand: 'The Athletes Co',
    country: 'KSA',
  },
  {
    id: '111184',
    name: 'Muhammed Azam',
    role_type: 'Support Function',
    new_role: 'Executive - Accounts',
    year: '2022',
    brand: 'Accounts and Finance',
    country: 'KSA',
  },
  {
    id: '111211',
    name: 'Mohammed Katpadi',
    role_type: 'Support Function',
    new_role: 'Executive - Accounts',
    year: '2022',
    brand: 'Accounts and Finance',
    country: 'KSA',
  },
  {
    id: '111269',
    name: 'Kamal Soby',
    role_type: 'Sales Back Office',
    new_role: 'Sales & Operations Manager',
    year: '2022',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '111301',
    name: 'Shamsudin Shafi',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '111321',
    name: 'Muhammad Roz dar',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
    IJP: true,
  },
  {
    id: '111327',
    name: 'Althaf Hussain',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '111339',
    name: 'Abdul Bareed',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '111343',
    name: 'Ibrahim Ramthu',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '111347',
    name: 'Shaik Hanif Chnnur',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '111711',
    name: 'Junaid Safdar',
    role_type: 'Sales Front Office',
    new_role: 'Area Sales Manager',
    year: '2022',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '112571',
    name: 'Saifulla Shaik Shaik',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
    IJP: true,
  },
  {
    id: '113489',
    name: 'Osama Mudher Alobed',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '113980',
    name: 'Mohamed Rauf Rizan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '114076',
    name: 'Arshad Shaik',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '114080',
    name: 'Shabaaz Mohammed',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '114870',
    name: 'Saif Alotaibi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '114921',
    name: 'Aisha Mohammed Hausawi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Ardene',
    country: 'KSA',
  },
  {
    id: '115176',
    name: 'Hussam Alsubhi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '116030',
    name: 'Emad Aldali',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '120892',
    name: 'Nada Alkhateri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Inglot',
    country: 'KSA',
  },
  {
    id: '120748',
    name: 'Rayan Fahad Abdullah Sharfan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '122290',
    name: 'Hussain Aldarwish',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '122630',
    name: 'Mohammed Mahmoud Younis Elsayed Mahdy',
    role_type: 'Support Function',
    new_role: 'Manager - Training ',
    year: '2022',
    brand: 'Training',
    country: 'KSA',
  },
  {
    id: '124223',
    name: 'Raid Dinh',
    role_type: 'Sales Front Office',
    new_role: 'Area Sales Manager',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '125460',
    name: 'Mohammed Arif Abdulrazak',
    role_type: 'Support Function',
    new_role: 'Executive - Accounts',
    year: '2022',
    brand: 'Accounts and Finance',
    country: 'KSA',
  },
  {
    id: '128778',
    name: 'Raheel Abdullah Saleh Alghamdi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'TOMS',
    country: 'KSA',
  },
  {
    id: '129440',
    name: 'Hassan Mohammed Alasmaeal',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '129486',
    name: 'Sahar Suhaiman Saleh Alshammeri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '129506',
    name: 'Bijah Haif Bijah Almutairi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '129718',
    name: 'Wasan Khalid Abdulhadi Alsubiani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '129731',
    name: 'Prabhakraan Chandrasekar',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
    IJP: true,
  },
  {
    id: '129733',
    name: 'Muhammad Waqas Muhammad Farooq',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
    IJP: true,
  },
  {
    id: '129797',
    name: 'Amjad Muqad Abdullah Almutairi',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '130013',
    name: 'Abdullah Hameed Alanazy',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '131617',
    name: 'Hamad Wahib Hamad Alwahiby',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '131699',
    name: 'Waad Naser Hasan Tahlwl',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '133365',
    name: 'Muhammed Shafi Saidh Muyarikandy',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '133457',
    name: 'Vishnu Narayanan',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '133845',
    name: 'Wathaq Emad Hassawi',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '133852',
    name: 'Abdalelah Jassem Alkhader',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '133928',
    name: 'Bader Mansour Muzal Alanazi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '133964',
    name: 'Riyadh Abdullah Mohammed Alfawzan',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Calvin Klein',
    country: 'KSA',
  },
  {
    id: '134000',
    name: 'Fatimah Yahya Gabby Mohazry',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
  },
  {
    id: '134091',
    name: 'Ahmed Salem Basheer Alkhaibari',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '134104',
    name: 'Nasser Ali Ibrahim Mujayri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '134252',
    name: 'Ameer Khaled Abdullah Alkhaldi',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2022',
    brand: 'R&B',
    country: 'KSA',
  },
  {
    id: '134333',
    name: 'Ashwaq Saleh Alsaleh',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Loss Prevention',
    country: 'KSA',
  },
  {
    id: '134490',
    name: 'Alwaleed Abdullah Saad Shuail',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Calvin Klein',
    country: 'KSA',
  },
  {
    id: '134551',
    name: 'Atif Mohammed Mohammed Alsindi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '134816',
    name: 'Amal Saad Ahmed Almalki',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Dune',
    country: 'KSA',
  },
  {
    id: '135072',
    name: 'Mohammed Khalifa Alawad',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '135435',
    name: 'Salman Saleh Albreet',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '135450',
    name: 'Orjwan Omar Hasan Mayan',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '135516',
    name: 'Nouf Abdulrahman Alsaad',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '135887',
    name: 'FASAL MOHAMMED TUFAIL',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
  },
  {
    id: '135892',
    name: 'MUZZAMIL NAWAZ',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
  },
  {
    id: '136917',
    name: 'MOHAMMED AHMED HASAN SUFYANI',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Beverly Hills Polo Club',
    country: 'KSA',
  },
  {
    id: '137327',
    name: 'Hussain Abdullah Saad Alqahtani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '137821',
    name: 'Rajapandiyan Thangavelu',
    role_type: 'Distribution Centre',
    new_role: 'DC Customer Service Assistant',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '137870',
    name: 'Aljin Krishnan',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
    IJP: true,
  },
  {
    id: '138035',
    name: 'Vignesh Mohanasundharam',
    role_type: 'Distribution Centre',
    new_role: 'DC Supervisor',
    year: '2022',
    brand: 'Distribution Centre',
    country: 'KSA',
  },
  {
    id: '138520',
    name: 'Agustin Tablate',
    role_type: 'Sales Front Office',
    new_role: 'Sushi Chef',
    year: '2022',
    brand: 'Sushi Library',
    country: 'KSA',
  },
  {
    id: '138551',
    name: 'Din Mohammad Nizam Uddin',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
  },
  {
    id: '138871',
    name: 'Alaa Mohammed',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '138936',
    name: 'Aseel Saad Yahya Al Qahtani',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '139521',
    name: 'Lubna Saud Abdulaziz Al Qwaiee',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
  },
  {
    id: '139522',
    name: 'Rayan Sutam Al Nwaibaghi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '139523',
    name: 'Hamad Jaber Hazazi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '139593',
    name: 'Hamoud Ahmed Zamri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '139729',
    name: 'Mohammed Abdullah Abdrabo Al Hubaishi',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Brand Bazaar',
    country: 'KSA',
  },
  {
    id: '139843',
    name: 'Shahad Ibrahim Abdulaziz Al Muzayni',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
  },
  {
    id: '139845',
    name: 'Khalid Nafa Swaad Al Mutari',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Calvin Klein',
    country: 'KSA',
  },
  {
    id: '140365',
    name: 'Thekra Abdulwahad Al Shehri',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
  },
  {
    id: '140450',
    name: 'Sultan Fahad Mohammed Al Harbi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '140821',
    name: 'Turki Abdullah Ali Al Shehri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Adidas',
    country: 'KSA',
  },
  {
    id: '140845',
    name: 'Hessah Suliman Ali Al Swayed',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Levis',
    country: 'KSA',
  },
  {
    id: '141007',
    name: 'Kholod Shafaq Alotaibi',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Tommy Hilfiger',
    country: 'KSA',
  },
  {
    id: '141063',
    name: 'Mashael Ali Ibrahem Altherwi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '141182',
    name: 'Yaser Bader Alotaibi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '141817',
    name: 'Moner Hussain Aljassim',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '143895',
    name: 'Usama Abbasi',
    role_type: 'Support Function',
    new_role: 'Inventory Control Assistant',
    year: '2022',
    brand: 'Inventory',
    country: 'KSA',
  },
  {
    id: '145883',
    name: 'Fadi Naaser Alharabi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '147338',
    name: 'Ali Musaed Alatefi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KSA',
  },
  {
    id: '148208',
    name: 'Rayan Ali Saleh Halabi',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Crocs',
    country: 'KSA',
  },
  {
    id: '148352',
    name: 'Suof Ahmed Mohammed Asiri',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Dune',
    country: 'KSA',
  },



]