import a109363 from '../assets/employee_images/109363.webp';
import a116023 from '../assets/employee_images/116023.webp';
import a119840 from '../assets/employee_images/119840.webp';
import a125751 from '../assets/employee_images/125751.webp';
import a132847 from '../assets/employee_images/132847.webp';
import a124296 from '../assets/employee_images/124296.webp';
import a126764 from '../assets/employee_images/126764.webp';
import a128771 from '../assets/employee_images/128771.webp';
import a134173 from '../assets/employee_images/134173.webp';
import a142344 from '../assets/employee_images/142344.webp';
import a109164 from '../assets/employee_images/109164.webp';
import a114191 from '../assets/employee_images/114191.webp';
import a133876 from '../assets/employee_images/133876.webp';
import a142101 from '../assets/employee_images/142101.webp';
import a142572 from '../assets/employee_images/142572.webp';
import a147165 from '../assets/employee_images/147165.webp';
import a159631 from '../assets/employee_images/159631.webp';
import a153411 from '../assets/employee_images/153411.webp';





export const kuwait_list = [

{
    id: '150375',
    name: 'Jigna Bharat Bhayani',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'July ',
    brand: 'Rituals',
    country: 'KUWAIT',
    // image: a150375,
  },
  {
    id: '153411',
    name: 'Krishna Bahadur Thapa',
    role_type: 'Sales Front Office',
    new_role: 'Manager - Restaurant',
    year: '2023',
    month: 'September',
    brand: 'Tim Hortons',
    country: 'KUWAIT',
    image: a153411,
  },
  {
    id: '109164',
    name: 'Michael Dulot',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'April',
    brand: 'Beverly Hills Polo Club',
    country: 'Kuwait',
    image: a109164,
  },
  {
    id: '114191',
    name: 'Ahrlot Duran Oasan',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'June',
    brand: 'Dune',
    country: 'Kuwait',
    image: a114191,
  },
  {
    id: '133876',
    name: 'Ramadan Abdelkhalek',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'June',
    brand: 'Dune',
    country: 'Kuwait',
    image: a133876,
  },
  {
    id: '137979',
    name: 'Roshan Subba',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'R&B',
    country: 'Kuwait',
    // image: a137979,
  },
  {
    id: '142101',
    name: 'Hend Abdelaziz Mohamed Sayed Ahmed',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'June',
    brand: 'Dune',
    country: 'Kuwait',
    image: a142101,
  },
  {
    id: '142572',
    name: 'Tandim Pem',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'June',
    brand: 'R&B',
    country: 'Kuwait',
    image: a142572,
  },
  {
    id: '147165',
    name: 'Tandin Wangchuk',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2023',
    month: 'May',
    brand: 'R&B',
    country: 'Kuwait',
    image: a147165,
  },
  {
    id: '159631',
    name: 'Shristy Karki',
    role_type: 'Sales Front Office',
    new_role: 'Supervisor',
    year: '2023',
    month: 'June',
    brand: 'Coldstone Creamery',
    country: 'Kuwait',
    image: a159631,
  },
  {
    id: '134173',
    name: 'Mohd Faisal',
    role_type: 'Ecommerce',
    new_role: 'Last Mile Supervisor',
    year: '2023',
    month: 'February',
    brand: '6th Street',
    country: 'KUWAIT',
    image: a134173,
  },
  {
    id: '109363',
    name: 'Mohammed Vellaiangal Imamuddin',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Birkenstock',
    country: 'KUWAIT',
    image: a109363,
  },
  {
    id: '116023',
    name: 'Ishworbahadur Shivabhakti',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Levis',
    country: 'KUWAIT',
    image: a116023,
  },
  {
    id: '119840',
    name: 'Ajay Gurung',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Edge',
    country: 'KUWAIT',
    image: a119840,
  },
  {
    id: '124296',
    name: 'Shankar Lama',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Aeropostale',
    country: 'KUWAIT',
    image: a124296,
  },
  {
    id: '125751',
    name: 'Ahmed Abdelwahab',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Dune',
    country: 'KUWAIT',
    image: a125751,
  },
  {
    id: '126764',
    name: 'Raiyan Patel',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Beverly Hills Polo Club',
    country: 'KUWAIT',
    image: a126764,
  },
  {
    id: '128771',
    name: 'Chetan Kalangutkar',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Brand Bazaar',
    country: 'KUWAIT',
    image: a128771,
  },
  {
    id: '132847',
    name: 'Islam Sewilam',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'Lakeland',
    country: 'KUWAIT',
    image: a132847,
  },
  {
    id: '142344',
    name: 'ARUN RAMESH',
    role_type: 'Sales Front Office',
    new_role: 'Cluster Manager',
    year: '2023',
    month: 'January',
    brand: 'HEMA',
    country: 'KUWAIT',
    image: a142344,
  },
  {
    id: '109137',
    name: 'Shrijana Gurung ',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Edge',
    country: 'KUWAIT',
  },
  {
    id: '109201',
    name: 'Arjun Gautam',
    role_type: 'Sales Front Office',
    new_role: 'Senior Sales Associate',
    year: '2022',
    brand: 'Skechers',
    country: 'KUWAIT',
  },
  {
    id: '109342',
    name: 'Mohammad Almaleh Emadaldeen',
    role_type: 'Sales Back Office',
    new_role: 'Senior Manager - Visual Merchandising',
    year: '2022',
    brand: 'Tommy Hilfiger',
    country: 'KUWAIT',
  },
  {
    id: '109392',
    name: 'Faizan Undre',
    role_type: 'Support Function',
    new_role: 'Senior Accountant',
    year: '2022',
    brand: 'Accounts and Finance',
    country: 'KUWAIT',
  },
  {
    id: '109748',
    name: 'Waleed Sayed Anter Mostafa',
    role_type: 'Sales Front Office',
    new_role: 'Manager - Operations',
    year: '2022',
    brand: 'Projects',
    country: 'KUWAIT',
  },
  {
    id: '112395',
    name: 'Vernne Lou Velasco Manansala',
    role_type: 'Sales Front Office',
    new_role: 'Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KUWAIT',
  },
  {
    id: '115901',
    name: 'Raul Ginde',
    role_type: 'Sales Front Office',
    new_role: 'Assistant Store Manager',
    year: '2022',
    brand: 'Skechers',
    country: 'KUWAIT',
  },
  {
    id: '118465',
    name: 'Reshika  Basnet',
    role_type: 'Sales Front Office',
    new_role: 'Department Head',
    year: '2022',
    brand: 'LC Waikiki',
    country: 'KUWAIT',
  },
  {
    id: '118466',
    name: 'Priscilla Shanti Rai',
    role_type: 'Sales Front Office',
    new_role: 'Department Head',
    year: '2022',
    brand: 'LC Waikiki',
    country: 'KUWAIT',
  },
  {
    id: '127214',
    name: 'Syed Zainulla',
    role_type: 'Support Function',
    new_role: 'Senior Executive - Human Capital',
    year: '2022',
    brand: 'Human Capital',
    country: 'KUWAIT',
  },
  {
    id: '135068',
    name: 'Jerold Palma',
    role_type: 'Sales Back Office',
    new_role: 'Assistant Manager - Visual Merchandising',
    year: '2022',
    brand: 'LC Waikiki',
    country: 'KUWAIT',
  },
  {
    id: '135204',
    name: 'Mahaboob Basha Shaik',
    role_type: 'Sales Front Office',
    new_role: 'Department Head',
    year: '2022',
    brand: 'LC Waikiki',
    country: 'KUWAIT',
  },
]