
import a107282 from '../assets/employee_images/107282.webp';
import a129663 from '../assets/employee_images/129663.webp';
import a107468 from '../assets/employee_images/107468.webp';
import a130444 from '../assets/employee_images/130444.webp';
import a131490 from '../assets/employee_images/131490.webp';
import a115493 from '../assets/employee_images/115493.webp';
import a126776 from '../assets/employee_images/126776.webp';
import a128448 from '../assets/employee_images/128448.webp';
import a128807 from '../assets/employee_images/128807.webp';
import a140620 from '../assets/employee_images/140620.webp';





export const oman_list = [
    {
        id: '107468',
        name: 'Mohammad Kamal',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'September',
        brand: 'The Childrens Place',
        country: 'OMAN',
        image: a107468,
      },
      {
        id: '130444',
        name: 'Subham Chettri',
        role_type: 'Sales Front Office',
        new_role: 'In-store Trainer',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'OMAN',
        image: a130444,
      },
      {
        id: '131490',
        name: 'Rakibul Hoque',
        role_type: 'Sales Front Office',
        new_role: 'In-store Trainer',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'OMAN',
        image: a131490,
      },
      {
        id: '115493',
        name: 'Andrew Roman Cortez',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2023',
        month: 'April',
        brand: 'Jamies Pizzeria',
        country: 'UAE',
        image: a115493,
      },
      {
        id: '126776',
        name: 'Umar  Khan',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'May',
        brand: 'Crocs',
        country: 'Oman',
        image: a126776,
      },
      {
        id: '128448',
        name: 'Romeo Jr. Portabes Cababat',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'May',
        brand: 'Charles & Keith',
        country: 'Oman',
        image: a128448,
      },
      {
        id: '128807',
        name: 'John Keneth Maningat Fruelda',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'May',
        brand: 'ALDO',
        country: 'Oman',
        image: a128807,
      },
      {
        id: '129663',
        name: 'Faisal Abdullah Saleh',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'May',
        brand: 'Beverly Hills Polo Club',
        country: 'Oman',
        image: a129663,
      },
      {
        id: '140620',
        name: 'Said Ali Said Amur Al Habsi',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'May',
        brand: 'Nine West',
        country: 'Oman',
        image: a140620,
      },
      {
        id: '107282',
        name: 'Arlyn Gentil',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2023',
        month: 'January',
        brand: 'R&B',
        country: 'OMAN',
        image: a107282,
      },
      {
        id: '107225',
        name: 'Abdul Kukarebettu',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Adidas',
        country: 'OMAN',
      },
      {
        id: '107261',
        name: 'Aishwarya Bajracharya',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '107264',
        name: 'Aiza Desacula',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Levis',
        country: 'OMAN',
      },
      {
        id: '107302',
        name: 'Chandan Paul',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107315',
        name: 'Danish Saiyad',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Dollar Plus',
        country: 'OMAN',
      },
      {
        id: '107346',
        name: 'Hemang Vora',
        role_type: 'Support Function',
        new_role: 'Assistant Manager',
        year: '2022',
        brand: 'Cost Analysis',
        country: 'OMAN',
      },
      {
        id: '107379',
        name: 'Jay Diezon',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107397',
        name: 'Juma Al Balushi',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107403',
        name: 'Krishna Pariyar',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107409',
        name: 'Kunal Subba',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Brand Bazaar',
        country: 'OMAN',
      },
      {
        id: '107418',
        name: 'Laxman Kotian',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107434',
        name: 'Mutasim Al Balushi',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107497',
        name: 'Prakit Ghatani',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '107537',
        name: 'Samana Aley',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Skechers',
        country: 'OMAN',
      },
      {
        id: '107546',
        name: 'Shamsa Al Ghammari',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Dune',
        country: 'OMAN',
      },
      {
        id: '107565',
        name: 'Safa Bakhsh Al Balushi',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Inglot',
        country: 'OMAN',
      },
      {
        id: '107592',
        name: 'Tariq Al Battashi',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '112267',
        name: 'Mohammad  Zeeshan',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'New Yorker',
        country: 'OMAN',
      },
      {
        id: '112271',
        name: 'Ryan Monis ',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'ALDO',
        country: 'OMAN',
      },
      {
        id: '120091',
        name: 'Daisheryl Canada',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '121196',
        name: 'Mohamed Arshad Ashraf',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '121640',
        name: 'Saleh Al Farsi',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '123975',
        name: 'Dipak  Bhujel',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '124230',
        name: 'Atif   Al Yahmadi',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Birkenstock',
        country: 'OMAN',
      },
      {
        id: '124648',
        name: 'Lyndon  Aroncillo',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'OMAN',
      },
      {
        id: '126476',
        name: 'Fawaz  Al Balushi',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '126477',
        name: 'Saad Al Waheibi',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Dune',
        country: 'OMAN',
      },
      {
        id: '126535',
        name: 'Gopinath  Saravanan ',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '126777',
        name: 'Zaheer khan  Mohammed',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Crocs',
        country: 'OMAN',
      },
      {
        id: '127301',
        name: 'Ahmed Ali Sadidn  Al Azkawi',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Crocs',
        country: 'OMAN',
      },
      {
        id: '127381',
        name: 'Arlyn  Berganio Soriano',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '127590',
        name: 'Fayaz  Khan',
        role_type: 'Sales Front Office',
        new_role: 'Graphic Designer',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '128493',
        name: 'Mohamed Badar  Hassan Al Balushi',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Beverly Hills Polo Club',
        country: 'OMAN',
      },
      {
        id: '128501',
        name: 'Kamrul Hassan',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Dollar Plus',
        country: 'OMAN',
      },
      {
        id: '128564',
        name: 'Ernaie Abagon  Gonzales',
        role_type: 'Sales Front Office',
        new_role: 'Senior Supervisor',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '128578',
        name: 'Jhun Veluz  Cerba',
        role_type: 'Sales Front Office',
        new_role: 'Junior Chef De Partie',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '128597',
        name: 'Kwister Kelvin Fernandes',
        role_type: 'Sales Front Office',
        new_role: 'Junior Chef De Partie',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '129122',
        name: 'Hafidha Murad Juma Al Balushi',
        role_type: 'Support Function',
        new_role: 'Assistant - Human Capital',
        year: '2022',
        brand: 'Human Capital',
        country: 'OMAN',
      },
      {
        id: '129156',
        name: 'Raymond Lepcha',
        role_type: 'Sales Front Office',
        new_role: 'Junior Chef De Partie',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '129158',
        name: 'Pravakar Pradhan',
        role_type: 'Sales Front Office',
        new_role: 'Senior waiter ',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '129605',
        name: 'Roshan Karki',
        role_type: 'Sales Front Office',
        new_role: 'Department Manager',
        year: '2022',
        brand: 'R&B',
        country: 'OMAN',
      },
      {
        id: '131319',
        name: 'Ahmed Elsherbini',
        role_type: 'Sales Front Office',
        new_role: 'Senior waiter ',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },
      {
        id: '134586',
        name: 'Chris Joy Tagbo',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2022',
        brand: 'Molten Chocolate Cafe',
        country: 'OMAN',
      },


]