import a108093 from '../assets/employee_images/108093.webp';
import a108281 from '../assets/employee_images/108281.webp';
import a108401 from '../assets/employee_images/108401.webp';
import a108822 from '../assets/employee_images/108822.webp';
import a108894 from '../assets/employee_images/108894.webp';
import a118237 from '../assets/employee_images/118237.webp';
import a118621 from '../assets/employee_images/118621.webp';
import a126560 from '../assets/employee_images/126560.webp';
import a126563 from '../assets/employee_images/126563.webp';
import a142391 from '../assets/employee_images/142391.webp';
import a124676 from '../assets/employee_images/124676.webp';
import a112321 from '../assets/employee_images/112321.webp';
import a108114 from '../assets/employee_images/108114.webp';
import a108368 from '../assets/employee_images/108368.webp';
import a112558 from '../assets/employee_images/112558.webp';
import a113277 from '../assets/employee_images/113277.webp';
import a114529 from '../assets/employee_images/114529.webp';
import a114542 from '../assets/employee_images/114542.webp';
import a114587 from '../assets/employee_images/114587.webp';
import a116499 from '../assets/employee_images/116499.webp';
import a117493 from '../assets/employee_images/117493.webp';
import a118310 from '../assets/employee_images/118310.webp';
import a123880 from '../assets/employee_images/123880.webp';
import a130050 from '../assets/employee_images/130050.webp';
import a134817 from '../assets/employee_images/134817.webp';
import a137004 from '../assets/employee_images/137004.webp';
import a137422 from '../assets/employee_images/137422.webp';
import a137423 from '../assets/employee_images/137423.webp';
import a141352 from '../assets/employee_images/141352.webp';
import a141776 from '../assets/employee_images/141776.webp';
import a145847 from '../assets/employee_images/145847.webp';





export const qatar_list = [
    {
        id: '124676',
        name: 'Priyadarshini Ravi',
        role_type: 'Support Function',
        new_role: 'Executive - Accounts',
        year: '2023',
        month: 'July ',
        brand: 'Accounts and Finance',
        country: 'QATAR',
        image: a124676,
      },
      {
        id: '112321',
        name: 'Ysabel Marfil',
        role_type: 'Sales Front Office',
        new_role: 'Manager - Restaurant',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a112321,
      },
      {
        id: '108114',
        name: 'Bernard Pia',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2023',
        month: 'July ',
        brand: 'Coldstone Creamery',
        country: 'QATAR',
        image: a108114,
      },
      {
        id: '108368',
        name: 'Jemimah Jane Dagalla Yana',
        role_type: 'Sales Front Office',
        new_role: 'In-store Trainer',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'QATAR',
        image: a108368,
      },
      {
        id: '112548',
        name: 'Jecel Rose Dalahigon Quintana',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Restaurant',
        year: '2023',
        month: 'July ',
        brand: 'Molten Chocolate Cafe',
        country: 'QATAR',
        // image: a112548,
      },
      {
        id: '112558',
        name: 'Shambhoo Gupta',
        role_type: 'Sales Front Office',
        new_role: 'Loss Prevention Associate',
        year: '2023',
        month: 'July ',
        brand: 'Loss Prevention',
        country: 'QATAR',
        image: a112558,
      },
      {
        id: '113277',
        name: 'Joyce Cayrel',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Restaurant',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a113277,
      },
      {
        id: '114529',
        name: 'Dhirendra Kumar',
        role_type: 'Sales Front Office',
        new_role: 'Senior Service Crew',
        year: '2023',
        month: 'July ',
        brand: 'Coldstone Creamery',
        country: 'QATAR',
        image: a114529,
      },
      {
        id: '114542',
        name: 'Manoj Thakur',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Restaurant',
        year: '2023',
        month: 'July ',
        brand: 'Jamies Pizzeria',
        country: 'QATAR',
        image: a114542,
      },
      {
        id: '114587',
        name: 'Nabindra Raj Giri',
        role_type: 'Sales Front Office',
        new_role: 'Head Chef',
        year: '2023',
        month: 'July ',
        brand: 'Jamies Italian',
        country: 'QATAR',
        image: a114587,
      },
      {
        id: '116499',
        name: 'Wilfred Dsouza',
        role_type: 'Support Function',
        new_role: 'Assistant Manager - Human Capital',
        year: '2023',
        month: 'July ',
        brand: 'Human Capital',
        country: 'QATAR',
        image: a116499,
      },
      {
        id: '117493',
        name: 'Muthuramalingam Manickam',
        role_type: 'Sales Front Office',
        new_role: 'Commis Chef',
        year: '2023',
        month: 'July ',
        brand: 'Jamies Italian',
        country: 'QATAR',
        image: a117493,
      },
      {
        id: '118310',
        name: 'Woseed Alam Khan',
        role_type: 'Sales Front Office',
        new_role: 'Kitchen Supervisor',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a118310,
      },
      {
        id: '123880',
        name: 'Dennis Jay Espidido Raneses',
        role_type: 'Sales Front Office',
        new_role: 'Lead Sushi Chef',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a123880,
      },
      {
        id: '130050',
        name: 'Nita Rai',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a130050,
      },
      {
        id: '134817',
        name: 'Hussein Mohamad Moussa',
        role_type: 'Sales Front Office',
        new_role: 'Area Sales Manager',
        year: '2023',
        month: 'July ',
        brand: 'Regional Office',
        country: 'QATAR',
        image: a134817,
      },
      {
        id: '137004',
        name: 'Ishan Baswani',
        role_type: 'Sales Front Office',
        new_role: 'Senior Host',
        year: '2023',
        month: 'July ',
        brand: 'Jamies Italian',
        country: 'QATAR',
        image: a137004,
      },
      {
        id: '137422',
        name: 'Beverly Bajado Delmonte',
        role_type: 'Sales Front Office',
        new_role: 'Sushi Chef',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a137422,
      },
      {
        id: '137423',
        name: 'Rovelyn Palic Andallo',
        role_type: 'Sales Front Office',
        new_role: 'Chef De Partie',
        year: '2023',
        month: 'July ',
        brand: 'Jamies Italian',
        country: 'QATAR',
        image: a137423,
      },
      {
        id: '141352',
        name: 'Jezalyn Duropan  Cabinian',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2023',
        month: 'July ',
        brand: 'Molten Chocolate Cafe',
        country: 'QATAR',
        image: a141352,
      },
      {
        id: '141776',
        name: 'Learmalyn Javier  Batalla',
        role_type: 'Sales Front Office',
        new_role: 'In-store Trainer',
        year: '2023',
        month: 'September',
        brand: 'Tim Hortons',
        country: 'QATAR',
        image: a141776,
      },
      {
        id: '145847',
        name: 'Fehzan Hamid Abdul Hamid Sheikh',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Restaurant',
        year: '2023',
        month: 'July ',
        brand: 'Sushi Library',
        country: 'QATAR',
        image: a145847,
      },
      {
        id: '108093',
        name: 'Abhilash Thakur',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Qatar',
        image: a108093,
      },
      {
        id: '108281',
        name: 'Girlie Rizabal',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Qatar',
        image: a108281,
      },
      {
        id: '108401',
        name: 'Jermaine Jersan Ibuyat',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Qatar',
        image: a108401,
      },
      {
        id: '108822',
        name: 'Roshni Bhujel',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Qatar',
        image: a108822,
      },
      {
        id: '108894',
        name: 'Santosh Dash',
        role_type: 'Ecommerce',
        new_role: 'Executive - Ecommerce',
        year: '2023',
        month: 'April',
        brand: 'R&B',
        country: 'Qatar',
        image: a108894,
      },
      {
        id: '118237',
        name: 'Nainsi Srivastava',
        role_type: 'Sales Front Office',
        new_role: 'Area Sales Manager',
        year: '2023',
        month: 'April',
        brand: 'Charles & Keith',
        country: 'Qatar',
        image: a118237,
      },
      {
        id: '118621',
        name: 'Mohammed Mafas Mohamed Lafeer',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Qatar',
        image: a118621,
      },
      {
        id: '126560',
        name: 'Adnan Ali Faruqui',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki',
        country: 'Qatar',
        image: a126560,
      },
      {
        id: '126563',
        name: 'Gianne Laylo Ilagan',
        role_type: 'Sales Front Office',
        new_role: 'Visual Merchandiser',
        year: '2023',
        month: 'April',
        brand: 'LC Waikiki Modest',
        country: 'Qatar',
        image: a126563,
      },
      {
        id: '142391',
        name: 'Arbaz Abdul Sattar  Khan',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Restaurant',
        year: '2023',
        month: 'April',
        brand: 'Tim Hortons',
        country: 'Qatar',
        image: a142391,
      },
      {
        id: '108079',
        name: 'Anil Lama',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'ALDO',
        country: 'QATAR',
      },
      {
        id: '108130',
        name: 'Bindu Khati',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'La Vie En Rose',
        country: 'QATAR',
      },
      {
        id: '108224',
        name: 'Emi Fujita',
        role_type: 'Support Function',
        new_role: 'Senior Executive - Human Capital',
        year: '2022',
        brand: 'Human Capital',
        country: 'QATAR',
      },
      {
        id: '108265',
        name: 'Govind Bhandari',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Sales',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '108270',
        name: 'Govinda Bhandari',
        role_type: 'Sales Front Office',
        new_role: 'Area Sales Manager',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '108302',
        name: 'Hazel Ello',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Levis',
        country: 'QATAR',
      },
      {
        id: '108422',
        name: 'John Harry Thuku',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Adidas',
        country: 'QATAR',
      },
      {
        id: '108477',
        name: 'Melody Gara',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Rituals',
        country: 'QATAR',
      },
      {
        id: '108521',
        name: 'Manoj Shrestha',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'QATAR',
      },
      {
        id: '108576',
        name: 'Michelle Cruz',
        role_type: 'Sales Front Office',
        new_role: 'Cluster Manager',
        year: '2022',
        brand: 'La Vie En Rose',
        country: 'QATAR',
      },
      {
        id: '108582',
        name: 'Mohammed Nizamudheen Cherak Kadath',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'New Yorker',
        country: 'QATAR',
      },
      {
        id: '108642',
        name: 'Nguwah Nguwah',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'ALDO Accessories',
        country: 'QATAR',
      },
      {
        id: '108695',
        name: 'Pankaj Singh Mahato',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'New Yorker',
        country: 'QATAR',
      },
      {
        id: '108713',
        name: 'Pradeep Kolathappilly Sasidharan',
        role_type: 'Sales Front Office',
        new_role: 'Area Sales Manager',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '108721',
        name: 'Raju Maharjan',
        role_type: 'Sales Front Office',
        new_role: 'Area Sales Manager',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '108764',
        name: 'Rahul Ayivalappil Chenni Chery',
        role_type: 'Support Function',
        new_role: 'Senior Executive - Loss Prevention',
        year: '2022',
        brand: 'Loss Prevention',
        country: 'QATAR',
      },
      {
        id: '108787',
        name: 'Rupesh Nepal',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Cool Club',
        country: 'QATAR',
      },
      {
        id: '108795',
        name: 'Rabin Subba',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'New Yorker',
        country: 'QATAR',
      },
      {
        id: '108799',
        name: 'Rosni Lama',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Nine West',
        country: 'QATAR',
      },
      //   {
      //     id: '108824',
      //     name: 'Sanjay Rai',
      //     role_type: 'Sales Front Office',
      //     new_role: 'Assistant Manager - Sales',
      //     year: '2022',
      //     brand: 'Regional Office',
      //     country: 'QATAR',
      //   },
      {
        id: '108846',
        name: 'Shila Shahi',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Skechers',
        country: 'QATAR',
      },
      {
        id: '108847',
        name: 'Shiva Ruchal Magar',
        role_type: 'Sales Front Office',
        new_role: 'Area Visual Merchandiser',
        year: '2022',
        brand: 'Brand Bazaar',
        country: 'QATAR',
      },
      {
        id: '108889',
        name: 'Shailendra Budhathoki',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Charles & Keith',
        country: 'QATAR',
      },
      {
        id: '108913',
        name: 'Saheb Dhakal',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'R&B Kids',
        country: 'QATAR',
      },
      {
        id: '108918',
        name: 'Sunil Sodari',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Skechers',
        country: 'QATAR',
      },
      {
        id: '108824',
        name: 'Sanjay Rai',
        role_type: 'Sales Back Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'The Childrens Place',
        country: 'QATAR',
      },
      {
        id: '108967',
        name: 'Takudzwa Mhizha',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Crocs',
        country: 'QATAR',
      },
      {
        id: '108983',
        name: 'Vabesh Rajbanshi',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'The Childrens Place',
        country: 'QATAR',
      },
      {
        id: '108998',
        name: 'Yanzee Sherpa',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Brand Bazaar',
        country: 'QATAR',
      },
      {
        id: '109013',
        name: 'Emad Atris',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Sales',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '112555',
        name: 'Bivek Bhandari',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'QATAR',
      },
      {
        id: '112767',
        name: 'Romit Lama',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Charles & Keith',
        country: 'QATAR',
      },
      {
        id: '112846',
        name: 'Abdullah Al Fayed',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'ALDO',
        country: 'QATAR',
      },
      {
        id: '112847',
        name: 'Mohammed Arshad',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Charles & Keith',
        country: 'QATAR',
      },
      {
        id: '113005',
        name: 'Abdelrhani Kachchab',
        role_type: 'Sales Front Office',
        new_role: 'Store Manager',
        year: '2022',
        brand: 'Birkenstock',
        country: 'QATAR',
      },
      {
        id: '113342',
        name: 'Tek Bahadur Pariyar',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Aeropostale',
        country: 'QATAR',
      },
      {
        id: '114137',
        name: 'Rakesh Kumar Verma',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'QATAR',
      },
      {
        id: '114532',
        name: 'Harish Kumar Rana',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2022',
        brand: 'Jamies Pizzeria',
        country: 'QATAR',
      },
      {
        id: '114592',
        name: 'Jeny Cunanan',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Rituals',
        country: 'QATAR',
      },
      {
        id: '116973',
        name: 'Amit Kumar Prasad',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Sales',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '118926',
        name: 'Pankaj Chandra Bhatt',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'QATAR',
      },
      {
        id: '119113',
        name: 'Malki Sandunika Silva Thenahandi',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'R&B Kids',
        country: 'QATAR',
      },
      {
        id: '119557',
        name: 'Manpreet Singh Bedi',
        role_type: 'Sales Front Office',
        new_role: 'Senior Visual Merchandiser',
        year: '2022',
        brand: 'Levis',
        country: 'QATAR',
      },
      {
        id: '121388',
        name: 'Raguraman Muthulingam',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Lakeland',
        country: 'QATAR',
      },
      {
        id: '121773',
        name: 'Achraf Bakka',
        role_type: 'Sales Front Office',
        new_role: 'Senior Sales Associate',
        year: '2022',
        brand: 'Tommy Hilfiger',
        country: 'QATAR',
      },
      {
        id: '121784',
        name: 'Dipen Rai',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Crocs',
        country: 'QATAR',
      },
      {
        id: '122388',
        name: 'Jyoti Rai',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Charles & Keith',
        country: 'QATAR',
      },
      {
        id: '123029',
        name: 'Dewash Rai',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Call It Spring',
        country: 'QATAR',
      },
      {
        id: '123049',
        name: 'Samten Lama',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Brand Bazaar',
        country: 'QATAR',
      },
      {
        id: '123288',
        name: 'Charmaine Tabajonda Gonzales',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Calvin Klein',
        country: 'QATAR',
      },
      {
        id: '123472',
        name: 'Kumar Baibhaw',
        role_type: 'Sales Front Office',
        new_role: 'Area Sales Manager',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '123718',
        name: 'Mitalkumar Ramtirth Yadav',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Tommy Hilfiger',
        country: 'QATAR',
      },
      {
        id: '124019',
        name: 'Jessa Colambot Brigoli',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'XIMIVOGUE',
        country: 'QATAR',
      },
      {
        id: '124196',
        name: 'Saurabh Bhasin',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Manager - Sales',
        year: '2022',
        brand: 'Regional Office',
        country: 'QATAR',
      },
      {
        id: '124520',
        name: 'Hemant Pratap Singh Gehlot',
        role_type: 'Support Function',
        new_role: 'Assistant Manager - Projects',
        year: '2022',
        brand: 'Projects',
        country: 'QATAR',
      },
     
      {
        id: '124634',
        name: 'Sanjay Pant',
        role_type: 'Distribution Centre',
        new_role: 'Senior DC Assistant',
        year: '2022',
        brand: 'Distribution Centre',
        country: 'QATAR',
      },
      {
        id: '125234',
        name: 'Edwin Mutuma William ',
        role_type: 'Sales Front Office',
        new_role: 'Senior Sales Associate',
        year: '2022',
        brand: 'Calvin Klein',
        country: 'QATAR',
      },
      {
        id: '126478',
        name: 'Gaurav Kumar Pradeep Kumar',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Levis',
        country: 'QATAR',
      },
      {
        id: '126499',
        name: 'Rajesh Kumar Kannan',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'QATAR',
      },
      {
        id: '126573',
        name: 'Paras Kumar Ramadhar Sharma',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'QATAR',
      },
      {
        id: '126726',
        name: 'Reynold Smith Sunil Smith',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Adidas',
        country: 'QATAR',
      },
      {
        id: '126854',
        name: 'Jeffrey Inacay Garbida',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Levis',
        country: 'QATAR',
      },
      {
        id: '127427',
        name: 'Marwa Briki',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'Tommy Hilfiger',
        country: 'QATAR',
      },
      {
        id: '127433',
        name: 'Patrick Denny Manjooran',
        role_type: 'Sales Front Office',
        new_role: 'Supervisor',
        year: '2022',
        brand: 'Jamies Italian',
        country: 'QATAR',
      },
      {
        id: '127619',
        name: 'Lina Boufrahi',
        role_type: 'Sales Front Office',
        new_role: 'Senior Sales Associate',
        year: '2022',
        brand: 'Charles & Keith',
        country: 'QATAR',
      },
      {
        id: '128465',
        name: 'Karan Dutta',
        role_type: 'Sales Front Office',
        new_role: 'Assistant Store Manager',
        year: '2022',
        brand: 'R&B',
        country: 'QATAR',
      },
      {
        id: '131702',
        name: 'Naushad Alam',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Dollar Plus',
        country: 'QATAR',
      },
      {
        id: '132531',
        name: 'Kishore Mysore Subramanya',
        role_type: 'Distribution Centre',
        new_role: 'Senior DC Assistant',
        year: '2022',
        brand: 'Distribution Centre',
        country: 'QATAR',
      },
      {
        id: '133381',
        name: 'Karan Limbu',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Dollar Plus',
        country: 'QATAR',
      },
      {
        id: '134857',
        name: 'Abul Hasan',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Dollar Plus',
        country: 'QATAR',
      },
      {
        id: '134860',
        name: 'Nahid Ahmed Soyef Uddin',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'XIMIVOGUE',
        country: 'QATAR',
      },
      {
        id: '134907',
        name: 'Jahid Hasan Abdur Rahman',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'QATAR',
      },
      {
        id: '134910',
        name: 'Mohammad Sobuz Hafiz Ullah',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'R&B',
        country: 'QATAR',
      },
      {
        id: '134913',
        name: 'Zahirul Talukder',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'R&B',
        country: 'QATAR',
      },
      {
        id: '134994',
        name: 'Din Islam Aminul Haque',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'LC Waikiki',
        country: 'QATAR',
      },
      {
        id: '135607',
        name: 'Yubaraj Pariyar',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'Naturalizer',
        country: 'QATAR',
      },
      {
        id: '135699',
        name: 'Mohammad Kawsar Abul Kashem',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'HEMA',
        country: 'QATAR',
      },
      {
        id: '136858',
        name: 'Ripon Debnath',
        role_type: 'Sales Front Office',
        new_role: 'Sales Associate',
        year: '2022',
        brand: 'HEMA',
        country: 'QATAR',
      },
      {
        id: '140027',
        name: 'Arif Sajjad Khan',
        role_type: 'Support Function',
        new_role: 'Assistant - Inventory Scanning',
        year: '2022',
        brand: 'Inventory',
        country: 'QATAR',
      },







]